/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package de.upb.cs.swt.delphi.crawler.io.swagger.client.model

import org.joda.time.DateTime
import java.util.UUID
import de.upb.cs.swt.delphi.crawler.io.swagger.client.core.ApiModel

case class Instance (
  iD: Option[Long],
  iP: Option[String],
  portnumber: Option[Long],
  name: Option[String],
  /* Component Type */
  componentType: Option[InstanceEnums.ComponentType]
) extends ApiModel

object InstanceEnums {

  type ComponentType = ComponentType.Value
  object ComponentType extends Enumeration {
    val Crawler = Value("Crawler")
    val WebApi = Value("WebApi")
    val WebApp = Value("WebApp")
    val DelphiManagement = Value("DelphiManagement")
  }

}

