/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package de.upb.cs.swt.delphi.crawler.io.swagger.client.model

import de.upb.cs.swt.delphi.crawler.io.swagger.client.core.ApiModel

case class InstanceID (
  iD: Option[Long]
) extends ApiModel


